title: Cohen Project
author: Avanish Kulkarni
email: avanishkulkarni03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the final project website.

# social links
github_username:  NoxiousFumes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
