title: Cohen Project
author: Yoinst Jiblet
email: bigfatnotebook@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Project for going through the github pages tutorial.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
